# NumPy

## 1. 创建数组

In [1]:
import numpy as np

通过 python 数组创建

In [2]:
a = np.array([1, 2, 3])
print('a:', a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print('b:', b)

a: [1 2 3]
b: [[1 2 3]
 [4 5 6]]


常用数组的创建

In [3]:
# 全 0 数组
c = np.zeros((2, 2))
print('c:', c)

# 全 1 数组
d = np.ones((1, 2))
print('d:', d)

# 使用 7 填充数组
e = np.full((2, 3), 7)
print('e:', e)

# 单位矩阵
f = np.eye(3)
print('d:', d)

# 随机数
g = np.random.random((2, 2))
print('g:', g)

c: [[0. 0.]
 [0. 0.]]
d: [[1. 1.]]
e: [[7 7 7]
 [7 7 7]]
d: [[1. 1.]]
g: [[0.74486886 0.30419223]
 [0.60807073 0.08296594]]


## 2. 访问数组中的元素

In [4]:
# 获取数组的大小
print('size of c:', c.size)

size of c: 4


In [5]:
# 获取数组的维度
print('shape of d:', d.shape)

shape of d: (1, 2)


In [6]:
print('a[0]:', a[0])

a[0]: 1


In [7]:
print('e[1]:', e[1])

e[1]: [7 7 7]


## 3. 广播

下面以一个 4x3 的二维数组和一个 1x3 的数组相加的例子，来说明 NumPy 中的广播计算

In [8]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 4, 5])

In [9]:
print('shape of x:', x.shape)
print('shape of v:', v.shape)

shape of x: (4, 3)
shape of v: (3,)


我们的目标是让 x 的每行和 v 中对应的元素相加：

**方法一**：通过 for 循环来实现

In [10]:
y = np.empty_like(x) # 创建一个和 x 维度相同的数组

for i in range(4):
    y[i, :] = x[i, :] + v
    
print('y:', y)

y: [[ 2  6  8]
 [ 5  9 11]
 [ 8 12 14]
 [11 15 17]]


**方法二**：广播

In [11]:
y = x + v
print('y:', y)

y: [[ 2  6  8]
 [ 5  9 11]
 [ 8 12 14]
 [11 15 17]]


对比上面的两种方法可以发现：
1. 使用 NumPy 中的广播计算，可以替代 for 循环
2. 代码看起来更加简洁

除此之外，广播相比与 for 循环计算速度更快，当然，广播也有一个缺点就是如果计算有问题，比较难以调试。所以，使用广播计算时应该保持清醒的头脑，理解计算前后数组维度的变化